{% set version = "0.7.0" %}
{% set number = "1" %}

package:
  name: ammolite
  version: {{ version }}

source:
  url: https://github.com/biotite-dev/ammolite/archive/v{{ version }}.tar.gz
  sha256: 7dcf4a08e42e0b3a514fbc860b3cd8584a80ac549ad7d18f631ff6320f2cfc7d

build:
  number: {{ number }}
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py < 37]
  skip: true  # [osx]

requirements:
  host:
    - python
    - pip
    - poetry
  run:
    - python
    - biotite >=0.22
    - pymol-open-source

test:
  files:
    - test.py
  commands:
    - python test.py

about:
  home: https://ammolite.biotite-python.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Visualize structure data from Biotite with PyMOL
  doc_url: https://ammolite.biotite-python.org
  dev_url: https://github.com/biotite-dev/ammolite

extra:
  recipe-maintainers:
    - padix-key
