{% set version = "0.5.0" %}
{% set number = "1" %}

package:
  name: ammolite
  version: {{ version }}

source:
  url: https://github.com/biotite-dev/ammolite/archive/v{{ version }}.tar.gz
  sha256: 83b9c72854d7742de13ee11e734b11940f51be9f108f2f0850b0907bded33711

build:
  number: {{ number }}
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
    - poetry
  run:
    - python >=3.7
    - biotite >=0.22
    - pymol-open-source

test:
  files:
    - test.py
  commands:
    - python test.py

about:
  home: https://ammolite.biotite-python.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Visualize structure data from Biotite with PyMOL
  doc_url: https://ammolite.biotite-python.org
  dev_url: https://github.com/biotite-dev/ammolite

extra:
  recipe-maintainers:
    - padix-key
